=== curiousan/sampleHospital/sampleHospital/target/sampleHospital/WEB-INF/classes/mySchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<xs:schema    xmlns:xs="http://www.w3.org/2001/XMLSchema"
              targetNamespace="http://www.w3schools.com"

              elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType mixed="true">
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="users">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:element name="user">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="fullName" type="xs:string"/> 
                    <xs:element name="sex" type="xs:string"/> 
                    <xs:element name="age" type="xs:string"/> 
                    <xs:element name="phoneNo" type="xs:string"/>
                    <xs:element name="address" type="xs:string"/> 
                    <xs:element name ="title" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="code" type="xs:string"/>
                </xs:complexType>
              </xs:element> <!-- name -->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== curiousan/sampleHospital/sampleHospital/target/sampleHospital/WEB-INF/classes/Storage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<root
    xmlns="http://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3schools.com mySchema.xsd">
    
    <users>   
        <user code="10">
            <fullName>sandesh poudel</fullName>
            <sex>male</sex>
            <age>19</age>
            <phoneNo>239239</phoneNo>
            <address>Rasinkatu 13</address> 
            <title>owner</title> 

        </user>
        <user code ="20">
            <fullName>Surendra pandey</fullName>
            <sex>male</sex>
            <age>22</age>
            <phoneNo>3432</phoneNo>
            <address>kilo 13</address>
            <title>manager</title> 
 
        </user>
        <user code ="40">
            <fullName>sangam poudel</fullName>
            <sex>male</sex>
            <age>22</age>
            <phoneNo>239239</phoneNo>
            <address>sydney</address> 
            <title>Programmer</title> 

        </user>
    </users>
   
    
</root>
